### ISSUE TITLE
Deployment fails

### ISSUE THREAD

**Issue by thesteve0** [Microsoft/openshift-origin#18]
I followed the instructions and set up the json file. I have a security principal named bigdatasp. I use the following command to instantiate the cluster:

>az group deployment create --resource-group bigdata --template-file azuredeploy.json --parameters @azuredeploy.parameters.json

and I get this error

_Deployment failed. {
  "status": "Failed",
  "error": {
    "code": "ResourceDeploymentFailure",
    "message": "The resource operation completed with terminal provisioning state 'Failed'.",
    "details": [
      {
        "code": "DeploymentFailed",
        "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.",
        "details": [
          {
            "code": "Conflict",
            "message": "{\r\n  \"status\": \"Failed\",\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n    \"details\": [\r\n      {\r\n        \"code\": \"VMExtensionProvisioningError\",\r\n        \"message\": \"VM has reported a failure when processing extension 'deployOpenShift'. Error message: \\\"Enable failed: failed to execute command: command terminated with exit status=4\\\".\"\r\n      }\r\n    ]\r\n  }\r\n}"
          }
        ]
      }
    ]
  }
}_

And this is all I get in the Portal

_{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.","details":[{"code":"Conflict","message":"{\r\n \"status\": \"Failed\",\r\n \"error\": {\r\n \"code\": \"ResourceDeploymentFailure\",\r\n \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n \"details\": [\r\n {\r\n \"code\": \"VMExtensionProvisioningError\",\r\n \"message\": \"VM has reported a failure when processing extension 'deployOpenShift'. Error message: \\\"Enable failed: failed to execute command: command terminated with exit status=4\\\".\"\r\n }\r\n ]\r\n }\r\n}"}]}_

I am not sure how to debug at this point.

**Comment by dewolfs** [comment]
I get the same error during deployment

**Comment by BastiOfBerlin** [comment]
To cite from the docs:

> For further troubleshooting, please SSH into your master0 node on port 2200. You will need to be root (sudo su -) and then navigate to the following directory: /var/lib/waagent/custom-script/download
You should see a folder named '0' and '1'. In each of these folders, you will see two files, stderr and stdout. You can look through these files to determine where the failure occurred.

**Comment by dewolfs** [comment]
**0/stderr + stdout -> no errors

1/stdout**

RUNNING HANDLER [restart origin-node] ******************************************
fatal: [testcl-infra-0]: FAILED! => {"changed": false, "failed": true, "msg": "Unable to restart service origin-node: Job for origin-node.service failed because the control process exited with error code. See \"systemctl status origin-node.service\" and \"journalctl -xe\" for details.\n"}
        to retry, use: --limit @/home/sysadmin/setup-azure-node.retry


**"systemctl status origin-node.service -l" output is**

Jul 26 10:28:48 testcl-master-0 origin-node[66616]: I0726 10:28:48.149655   66616 conversion.go:134] failed to handle multiple devices for container. Skipping Filesystem stats
Jul 26 10:28:48 testcl-master-0 origin-node[66616]: I0726 10:28:48.149699   66616 conversion.go:134] failed to handle multiple devices for container. Skipping Filesystem stats
Jul 26 10:28:50 testcl-master-0 origin-node[66616]: I0726 10:28:50.475079   66616 kubelet_node_status.go:230] Controller attach/detach is disabled for this node; Kubelet will attach and detach volumes
Jul 26 10:28:50 testcl-master-0 origin-node[66616]: E0726 10:28:50.533784   66616 kubelet_node_status.go:70] Unable to construct api.Node object for kubelet: failed to get external ID from cloud provider: compute.VirtualMachinesClient#Get: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthorizationFailed" Message="The client '8e4cc5fb-7e6d-41ae-ac20-7eb49dcbf582' with object id '8e4cc5fb-7e6d-41ae-ac20-7eb49dcbf582' does not have authorization to perform action 'Microsoft.Compute/virtualMachines/read' over scope '/subscriptions/bc1d24d7-eb31-4f7b-ba09-95d50995b27f/resourceGroups/rg-test-azure-bootcamp-openshift/providers/Microsoft.Compute/virtualMachines/testcl-master-0'."
Jul 26 10:28:57 testcl-master-0 origin-node[66616]: I0726 10:28:57.534006   66616 kubelet_node_status.go:230] Controller attach/detach is disabled for this node; Kubelet will attach and detach volumes
Jul 26 10:28:57 testcl-master-0 origin-node[66616]: E0726 10:28:57.578879   66616 kubelet_node_status.go:70] Unable to construct api.Node object for kubelet: failed to get external ID from cloud provider: compute.VirtualMachinesClient#Get: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthorizationFailed" Message="The client '8e4cc5fb-7e6d-41ae-ac20-7eb49dcbf582' with object id '8e4cc5fb-7e6d-41ae-ac20-7eb49dcbf582' does not have authorization to perform action 'Microsoft.Compute/virtualMachines/read' over scope '/subscriptions/bc1d24d7-eb31-4f7b-ba09-95d50995b27f/resourceGroups/rg-test-azure-bootcamp-openshift/providers/Microsoft.Compute/virtualMachines/testxcl-master-0'."
Jul 26 10:28:58 testcl-master-0 origin-node[66616]: I0726 10:28:58.181659   66616 conversion.go:134] failed to handle multiple devices for container. Skipping Filesystem stats
Jul 26 10:28:58 testcl-master-0 origin-node[66616]: I0726 10:28:58.181693   66616 conversion.go:134] failed to handle multiple devices for container. Skipping Filesystem stats
Jul 26 10:29:04 testcl-master-0 origin-node[66616]: I0726 10:29:04.579768   66616 kubelet_node_status.go:230] Controller attach/detach is disabled for this node; Kubelet will attach and detach volumes
Jul 26 10:29:04 testcl-master-0 origin-node[66616]: E0726 10:29:04.631465   66616 kubelet_node_status.go:70] Unable to construct api.Node object for kubelet: failed to get external ID from cloud provider: compute.VirtualMachinesClient#Get: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthorizationFailed" Message="The client '8e4cc5fb-7e6d-41ae-ac20-7eb49dcbf582' with object id '8e4cc5fb-7e6d-41ae-ac20-7eb49dcbf582' does not have authorization to perform action 'Microsoft.Compute/virtualMachines/read' over scope '/subscriptions/bc1d24d7-eb31-4f7b-ba09-95d50995b27f/resourceGroups/rg-test-azure-bootcamp-openshift/providers/Microsoft.Compute/virtualMachines/testcl-master-0'."


the objectid is the serviceprincple. To troubleshoot it, I gave it contributor rights on the subscription level but still get the same error.

**Comment by BorisB2015** [comment]
@dewolfs - thank you for the detailed error info! I will try to deploy the most recent template myself and see if I get errors and will comment on which GUID to use where - wanted to verify that readme instructions are clear. Once I get to try it first hand I will put commands on how to verify that your service principal has access (in short, you need to check via CLI that you can read VMs with its credentials).

@thesteve0 - do you have similar output in your cluster to see what might be failing? Thanks!

**Comment by dewolfs** [comment]
@BorisB2015 were you able to execute a test deployment?

**Comment by tanaka-takayoshi** [comment]
Hello, I also tried the latest template and got a similar error.
The stderror files under /var/lib/waagent/custom-script/download/{0.1} say:

0/stderr
```
warning: /var/cache/yum/x86_64/7/epel/packages/ansible-2.3.1.0-1.el7.noarch.rpm: Header V3 RSA/SHA256 Signature, key ID 352c64e5: NOKEY
Importing GPG key 0x352C64E5:
 Userid     : "Fedora EPEL (7) <epel@fedoraproject.org>"
 Fingerprint: 91e9 7d7c 4a5e 96f1 7f3e 888f 6a2f aea2 352c 64e5
 Package    : epel-release-7-10.noarch (installed)
 From       : /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7
INFO: Volume group backing root filesystem could not be determined
File descriptor 10 (/dev/urandom) leaked on vgs invocation. Parent PID 1726: /bin/bash
File descriptor 11 (/dev/urandom) leaked on vgs invocation. Parent PID 1726: /bin/bash
File descriptor 10 (/dev/urandom) leaked on pvs invocation. Parent PID 1748: /bin/bash
File descriptor 11 (/dev/urandom) leaked on pvs invocation. Parent PID 1748: /bin/bash
Checking that no-one is using this disk right now ...
OK
sfdisk:  /dev/sdb: unrecognized partition table type

sfdisk: No partitions found

Warning: partition 1 does not end at a cylinder boundary
Warning: no primary partition is marked bootable (active)
This does not matter for LILO, but the DOS MBR will not boot this disk.
If you created or changed a DOS partition, /dev/foo7, say, then use dd(1)
to zero the first 512 bytes:  dd if=/dev/zero of=/dev/foo7 bs=512 count=1
(See fdisk(8).)
INFO: Device node /dev/sdb1 exists.
File descriptor 10 (/dev/urandom) leaked on pvcreate invocation. Parent PID 1726: /bin/bash
File descriptor 11 (/dev/urandom) leaked on pvcreate invocation. Parent PID 1726: /bin/bash
File descriptor 10 (/dev/urandom) leaked on vgcreate invocation. Parent PID 1726: /bin/bash
File descriptor 11 (/dev/urandom) leaked on vgcreate invocation. Parent PID 1726: /bin/bash
File descriptor 10 (/dev/urandom) leaked on vgs invocation. Parent PID 1726: /bin/bash
File descriptor 11 (/dev/urandom) leaked on vgs invocation. Parent PID 1726: /bin/bash
File descriptor 10 (/dev/urandom) leaked on lvs invocation. Parent PID 1797: /bin/bash
File descriptor 11 (/dev/urandom) leaked on lvs invocation. Parent PID 1797: /bin/bash
File descriptor 10 (/dev/urandom) leaked on vgs invocation. Parent PID 1726: /bin/bash
File descriptor 11 (/dev/urandom) leaked on vgs invocation. Parent PID 1726: /bin/bash
File descriptor 10 (/dev/urandom) leaked on vgs invocation. Parent PID 1807: /bin/bash
File descriptor 11 (/dev/urandom) leaked on vgs invocation. Parent PID 1807: /bin/bash
File descriptor 10 (/dev/urandom) leaked on vgs invocation. Parent PID 1726: /bin/bash
File descriptor 11 (/dev/urandom) leaked on vgs invocation. Parent PID 1726: /bin/bash
File descriptor 10 (/dev/urandom) leaked on lvcreate invocation. Parent PID 1726: /bin/bash
File descriptor 11 (/dev/urandom) leaked on lvcreate invocation. Parent PID 1726: /bin/bash
File descriptor 10 (/dev/urandom) leaked on lvs invocation. Parent PID 1856: /bin/bash
File descriptor 11 (/dev/urandom) leaked on lvs invocation. Parent PID 1856: /bin/bash
File descriptor 10 (/dev/urandom) leaked on lvm invocation. Parent PID 1905: /bin/bash
File descriptor 11 (/dev/urandom) leaked on lvm invocation. Parent PID 1905: /bin/bash
File descriptor 10 (/dev/urandom) leaked on lvchange invocation. Parent PID 1726: /bin/bash
File descriptor 11 (/dev/urandom) leaked on lvchange invocation. Parent PID 1726: /bin/bash
Created symlink from /etc/systemd/system/multi-user.target.wants/docker.service to /usr/lib/systemd/system/docker.service.
Error: Package: 1:nodejs-6.11.1-1.el7.x86_64 (epel)
           Requires: libhttp_parser.so.2()(64bit)
Error: Package: 1:nodejs-6.11.1-1.el7.x86_64 (epel)
           Requires: http-parser >= 2.7.0
masterPrep.sh: line 77: npm: command not found
```

1/stderr
```
deployOpenShift.sh: line 37: azure: command not found
```

**Comment by BorisB2015** [comment]
Finally got time to do work/troubleshooting on this.

@dewolfs: for the error of service principal not having access to the group, I found the following sequence useful. 

I'm using Azure CLI 2.0 (az) as I want to avoid using Azure CLI 1.0 (azure).

1. As I debug deployments, I created the service principal with permission grant as outlined in ReadMe, step 1.
2. Then as I kept getting through failures, I found it easier to delete the group and create a brand new one and grant permission of the already created service principal to this new group. So the sequence looks as follows (on my deployment machine):

```` bash 
az group delete --name OpenShiftOriginTest4 --no-wait
az group create --name OpenShiftOriginTest5 --location westus2
az role assignment create --assignee c0cc91fd-4751-4a53-9795-902349eedbfd --resource-group OpenShiftOriginTest5 --role Contributor
# GUID here is appId value I got when I created the service principal - see example output in the readme
az group deployment create --resource-group OpenShiftOriginTest5 --template-file azuredeploy.json --parameters @azuredeploy.parameters.local.json --no-wait
````

**Note** that if you are not modifying the parameters in the local file you need to wait for deletion of the prior group at least to the point of deleting public IPs or you will hit DNS conflict error. It usually takes a minute or two.

I also added step 3 in the ReadMe [currently in my own repo](https://github.com/BorisB2015/openshift-origin/blob/master/README.md) to explain the above.

You could also check that grant worked fine by running:

`az role assignment list --resource-group OpenShiftOriginTest5`

You should see non-empty output with at least one line corresponding to your Service Principal.

2 values from service principal creation (appId and password) go into the template parameters `aadClientId` and `aadClientSecret`, respectively.

**Comment by BorisB2015** [comment]
@tanaka-takayoshi: the error you get is due to changes in the installation of Azure CLI 1.0 (azure) dependencies. I'm trying to replace this with Azure CLI 2.0 as [shown here](https://github.com/BorisB2015/openshift-origin/commit/3511ac902e77b35d3d2fe6e33fa68a4cd90bb6d4#diff-5122bd37142550977e7f76c928502618).

Currently I'm past point of dependencies and updating the template in my repo to pick up recently released Origin 1.6 (as there is a dependencies mismatch and older 1.5 version has been specified in deployOpenShift.sh).

Assuming I get through this - I will post another update as I get things working and submit PR to the main repo.

**Comment by santab** [comment]
@BorisB2015: the `masterPrep.sh: line 77: npm: command not found` error is due to the yum install for nodejs failing due to [https://bugs.centos.org/view.php?id=13669&nbn=1](url). CentOS 7.4 should resolve this.

**Comment by haroldwongms** [comment]
We are removing the installation of the Azure CLI so this will no longer be an issue moving forward.  The latest changes should be live soon once Boris gets a chance to review.

Closing this issue.

Thank you.

Harold

**Comment by thesteve0** [comment]
Where is it moving to?

**Comment by haroldwongms** [comment]
thesteve0: not sure what you mean.  We are not moving it anywhere.  With the latest release, there is no longer a need to use the CLI as part of the deployment process.

**Comment by rcardona-os** [comment]
Hi @haroldwongms @BorisB2015 
First than all thx for all the work you do setting these templates up.
Regarding the mentioned error, I am still getting ..

Deployment failed. {
"status": "Failed",
"error": {
"code": "ResourceDeploymentFailure",
"message": "The resource operation completed with terminal provisioning state 'Failed'.",
"details": [
{
"code": "DeploymentFailed",
"message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.",
"details": [
{
"code": "Conflict",
"message": "{\r\n "status": "Failed",\r\n "error": {\r\n "code": "ResourceDeploymentFailure",\r\n "message": "The resource operation completed with terminal provisioning state 'Failed'.",\r\n "details": [\r\n {\r\n "code": "VMExtensionProvisioningError",\r\n "message": "VM has reported a failure when processing extension 'deployOpenShift'. Error message: \"Enable failed: failed to execute command: command terminated with exit status=4\"."\r\n }\r\n ]\r\n }\r\n}"
}

My azuredeploy.parameters.json is:

{
	"$schema": "http://schema.management.azure.com/schemas/2015-01-01/deploymentParameters.json#",
	"contentVersion": "1.0.0.0",
	"parameters": {
		"_artifactsLocation": {
			"value": "https://raw.githubusercontent.com/Microsoft/openshift-origin/master/"
		},
		"masterVmSize": {
			"value": "Standard_GS3"
		},
		"infraVmSize": {
			"value": "Standard_GS3"
		},
		"nodeVmSize": {
			"value": "Standard_GS3"
		},
		"openshiftClusterPrefix": {
			"value": "myorigincluster"
		},
		"masterInstanceCount": {
			"value": 3
		},
		"infraInstanceCount": {
			"value": 2
		},
		"nodeInstanceCount": {
			"value": 1
		},
		"dataDiskSize": {
			"value": 128
		},
		"adminUsername": {
			"value": "origin"
		},
		"openshiftPassword": {
			"value": "***thePassword***"
		},
		"sshPublicKey": {
			"value": "*** the ssh-rsa key*** "
		},
		"keyVaultResourceGroup": {
			"value": "BaseRG"
		},
		"keyVaultName": {
			"value": "OriginVault"
		},
		"keyVaultSecret": {
			"value": "OriginSecret"
		},
		"aadClientId": {
			"value": "*** the id***"
		},
		"aadClientSecret": {
			"value": "***thePassword***"
		},
		"defaultSubDomainType": {
			"value": "nipio"
		},
		"defaultSubDomain": {
			"value": "example.com"
		}
	}
}

Why am I getting the same error, what bit am I missing here?

Thank you very much in advance for your help.

Raf,

**Comment by mavis1827** [comment]
@rcardona-os were you able to bypass this failure? i'm running into exact failure now. Could you please provide the steps you took to fix this issue?
